import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { POPULAR } from "./src/popular-list";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

type Bang = {
    c: string;
    d: string;
    r: number;
    s: string;
    sc: string;
    t: string;
    u: string;
};

const baseFilePath = join(__dirname, "src", "bangs-base.ts");
const customFilePath = join(__dirname, "src", "custom-bangs.ts");
const outputPath = join(__dirname, "src", "bang.ts");
const popularOutputPath = join(__dirname, "src", "popular-bangs.ts");

function extractArray(content: string): Bang[] {
    const match = content.match(/export const \w+ = (\[[\s\S]*\]);/);
    if (!match) return [];
    return eval(match[1]);
}

try {
    console.log("Merging bangs...");

    const baseContent = readFileSync(baseFilePath, "utf-8");
    const baseBangs = extractArray(baseContent);
    console.log(`Base bangs: ${baseBangs.length}`);

    const bangMap = new Map(baseBangs.map((b) => [b.t, b]));

    let customBangs: Bang[] = [];
    try {
        const customContent = readFileSync(customFilePath, "utf-8");
        customBangs = extractArray(customContent);
        console.log(`Custom bangs: ${customBangs.length}`);
    } catch {
        console.log("No custom bangs file found; using base bangs only.");
    }

    const overwritten: string[] = [];
    const added: string[] = [];

    for (const b of customBangs) {
        if (bangMap.has(b.t)) {
            overwritten.push(b.t);
        } else {
            added.push(b.t);
        }
        bangMap.set(b.t, b);
    }

    const merged = Array.from(bangMap.values());

    writeFileSync(outputPath, `// Auto-generated by merge-bangs.ts\n\nexport const bangs = ${JSON.stringify(merged, null, 2)};\n`, "utf-8");

    console.log(`Wrote ${merged.length} bangs to src/bang.ts`);

    // Generate the small "popular" subset that is baked into the redirect
    // bundle, so common bangs resolve without loading the full dataset.
    const popularBangs: Bang[] = [];
    const missing: string[] = [];
    for (const { t } of POPULAR) {
        const b = bangMap.get(t);
        if (b) popularBangs.push(b);
        else missing.push(t);
    }
    writeFileSync(popularOutputPath, `// Auto-generated by merge-bangs.ts\n\nexport const popularBangs = ${JSON.stringify(popularBangs, null, 2)};\n`, "utf-8");
    console.log(`Wrote ${popularBangs.length} popular bangs to src/popular-bangs.ts`);
    if (missing.length) console.warn(`Popular triggers not found in dataset (${missing.length}): ${missing.join(", ")}`);
    if (overwritten.length) console.log(`Overwritten (${overwritten.length}): ${overwritten.join(", ")}`);
    if (added.length) console.log(`Added (${added.length}): ${added.join(", ")}`);
    console.log("Merge completed successfully");
} catch (err: any) {
    console.error("Merge failed:", err?.message ?? err);
    process.exit(1);
}
