// Source of truth for "popular" bangs.
//
// These are the most commonly used triggers. Their full bang data is baked
// into the redirect bundle (see popular-bangs.ts, generated by merge-bangs.ts)
// so the common case redirects instantly without loading the full ~2MB dataset.
//
// `t` is the bang trigger, `name` is the friendly display name shown in the
// default-engine dropdown. Order here is the order shown in the dropdown.

export const POPULAR: { t: string; name: string }[] = [
    { t: "g", name: "Google" },
    { t: "ddg", name: "DuckDuckGo" },
    { t: "b", name: "Bing" },
    { t: "brave", name: "Brave" },
    { t: "sp", name: "Startpage" },
    { t: "yt", name: "YouTube" },
    { t: "gh", name: "GitHub" },
    { t: "w", name: "Wikipedia" },
    { t: "t3", name: "T3 Chat" },
    { t: "ppx", name: "Perplexity" },
    { t: "cg", name: "ChatGPT" },
    { t: "a", name: "Amazon" },
    { t: "r", name: "Reddit" },
    { t: "so", name: "Stack Overflow" },
    { t: "maps", name: "Google Maps" },
    { t: "gm", name: "Google Maps" },
    { t: "tr", name: "Google Translate" },
    { t: "wa", name: "Wolfram Alpha" },
    { t: "npm", name: "npm" },
    { t: "mdn", name: "MDN" },
    { t: "imdb", name: "IMDb" },
    { t: "tw", name: "X (Twitter)" },
    { t: "x", name: "X (Twitter)" },
    { t: "gimg", name: "Google Images" },
    { t: "gs", name: "Google Shopping" },
    { t: "ghr", name: "GitHub Repo" },
    { t: "gf", name: "Google Finance" },
    { t: "ytm", name: "YouTube Music" },
    { t: "gmaps", name: "Google Maps" },
    { t: "gcal", name: "Google Calendar" },
    { t: "protonmail", name: "Proton Mail" },
];
